
spring:
  rabbitmq:
    username: rabbit_user
    password: rabbit_pass
  datasource:
    url: jdbc:postgresql://localhost:5432/seeker?${spring.datasource.connection-properties}
    username: seeker
    password: postgres
#  If set will create a new datasource just for liguibase
#  liquibase:
#    user:     seeker
#    password: postgres
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      dadosAbertosClient:
        loggerLevel: FULL

logging.level.me.efraimgentil.seeker.client.DadosAbertosClient: DEBUG