
spring:
  rabbitmq:
    username: rabbit_user
    password: rabbit_pass
  datasource:
    url: jdbc:postgresql://localhost:5432/seeker?stringtype=unspecified&ApplicationName=${spring.application.name}
    username: seeker
    password: postgres
    connection-properties: stringtype=unspecified;ApplicationName=${spring.application.name}
  liquibase:
    user:     seeker
    password: postgres
  jpa:
    show-sql: true


feign:
  client:
    config:
      dadosAbertosClient:
        loggerLevel: FULL

logging.level.me.efraimgentil.seeker.client.DadosAbertosClient: DEBUG