

server:
  port: 8090

spring:
  application:
    name: seeker
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: ${SEEKER_DATABASE_URL}?${spring.datasource.connection-properties}
    username: ${SEEKER_DB_USER}
    password: ${SEEKER_DB_PASS}
    connection-properties: stringtype=unspecified&ApplicationName=${spring.application.name}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 60000 # 1 min
      max-lifetime: 600000 # 10 minutes
      poolName: seeker-pool
# If set will create a new datasource just for liguibase
#  liquibase:
#    user:     ${SEEKER_MIGRATION_DB_USER:seeker}
#    password: ${SEEKER_MIGRATION_DB_PASS:postgres}

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

dadosAbertos:
  cotas:
    downloadUrl: "https://www.camara.leg.br/cotas"

feign:
  client:
    config:
      dadosAbertosClient:
        url: "https://dadosabertos.camara.leg.br/api/v2"
        loggerLevel: NONE

logging.level.root: INFO
logging.level.org.apache.commons.beanutils: INFO